parameters:
#    formation_model.example.class: Formation\ModelBundle\Example

services:
#    formation_model.example:
#        class: %formation_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
