parameters:
#    formation_user.example.class: Formation\UserBundle\Example

services:
#    formation_user.example:
#        class: %formation_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
